polls/urls.py
from django.conf.urls import patterns, include, url
from polls import views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'gettingstartedwithdjango.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', views.index, name='index'),
    url(r'^(?P<question_id>\d+)/$', views.detail, name='detail'),
    url(r'^(?P<question_id>\d+)/results/$', views.results, name='results'),
    url(r'^(?P<question_id>\d+)/vote/$', views.vote, name='vote'),
    url(r'^(?P<question_id>\d+)/comment/$', views.post_comment, name='comment'),
    url(r'^(?P<question_id>\d+)/delete/$', views.question_delete, name='question_delete'),
    url(r'^(?P<question_id>\d+)/sticky/$', views.question_sticky, name='question_sticky'),
    url(r'^comment/(?P<comment_id>[\d\w]+)/delete/$', views.comment_delete, name='comment_delete'),
    url(r'^login/$', views.login, name='login'),
    url(r'^post/$', views.post_poll, name='post'),
    url(r'^nick/$', views.create_nick, name='nick'),
)

polls/models.py
from django.db import models
from django.utils import timezone
import datetime
import string
import random
import hashlib

def rand_submitter_gen():
    r = ''.join(random.choice(string.lowercase[:6] + string.digits) for i in range(40));
    return r;
    
def comment_id_txt():
    m = hashlib.new('sha1');
    m.update(rand_submitter_gen());
    return m.hexdigest()[:6];

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200);
    pub_date = models.DateTimeField('date published', default=timezone.now);
    tagline = models.CharField(max_length=140, default="", blank=True);
    submitter = models.CharField(max_length=40, default=rand_submitter_gen);
    submitter_nick = models.CharField(max_length=20, default="", blank=True);
    description = models.CharField(max_length=10000, blank=True);
    last_modified = models.DateTimeField(auto_now=True, auto_now_add=True);
    sticky = models.BooleanField(default=False);
    
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1);
        
    was_published_recently.admin_order_field = 'pub_date';
    was_published_recently.boolean = True;
    was_published_recently.short_description = 'Published recently?';
    
    def __unicode__(self):
        return self.question_text;
    
class Choice(models.Model):
    question = models.ForeignKey(Question);
    choice_text = models.CharField(max_length=200);
    votes = models.IntegerField(default=0);
    
    def __unicode__(self):
        return self.choice_text;
        
class Comment(models.Model):
    question = models.ForeignKey(Question, related_name="comments");
    submitter = models.CharField(max_length=40);
    submitter_nick = models.CharField(max_length=20, default="", blank=True);
    text = models.CharField(max_length=10000);
    id_txt = models.CharField(max_length=6, default=comment_id_txt);
    
    def __unicode__(self):
        return self.text;
        
class Nick(models.Model):
    name = models.CharField(max_length=20);
    password_hash = models.CharField(max_length=40);
    admin = models.BooleanField(default=False);
    
    def verify_password(self, password):
        if(hashlib.sha1(password).hexdigest() == self.password_hash):
            return True;
        return False;
    
    '''
    Create a nick object with a password instead of a password hash
    '''
    @classmethod
    def create_password(cls, nick, password):
        return cls(name = nick, password_hash = hashlib.sha1(password).hexdigest());
    
    def __unicode__(self):
        return self.name;

polls/templates/polls/base.html
{% load staticfiles %}
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'polls/stickyFooter.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'polls/comments.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'polls/bootstrap-markdown.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" />
    
    <script src="https://code.jquery.com/jquery-2.1.3.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    
    {%block head%}{%endblock%}
    
    <title>POLLBOARD</title>
</head>
<body>
    <div class="modal fade" id="confirmIDModal" tabindex="-1" role="dialog" aria-labelledby="ConfirmIDChange" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4>Confirm ID Change</h4>
                </div>
                <div class="modal-body">
                    <p>Are you sure you want to change your ID?</p>
                    <p>You may get a pretty new color, and your nickname will stay the same, <b>but you will unable to modify polls made from a previous ID!</b></p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Never Mind</button>
                    <a href="{% url 'polls:login' %}?next={{ request.path|urlencode }}" type="button" class="btn btn-danger">Yes, change it</a>
                </div>
            </div>
        </div>
    </div>
    {%block modal%}{%endblock%}
    <h1 class="title">POLLBOARD</h1>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                {% if messages %}
                    {% for m in messages %}
                        {%if m.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                            <div class="alert alert-danger" role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                <b>ERROR:</b> {{m}}
                                </div>
                        {%elif m.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
                            <div class="alert alert-warning" role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                <b>Warning:</b> {{m}}
                            </div>
                        {%else%}
                            <div class="alert alert-info" role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                {{m}}
                            </div>
                        {%endif%}
                    {% endfor %}
                {%endif%}
            </div>
        </div>
        <div class="row">
            <div class="col-sm-3 col-lg-2">
                {% if uid != 0 %}
                    <div class="panel panel-default panel-sidebar">
                        <div class="panel-heading"><h4>User Panel</h4></div>
                        <div class="panel-body">
                            <div>Your id is:</div>
                            <p style="color: #{{uid|slice:'6'}};">{%if nick %}<b>[{{ nick.name }}] </b>{%endif%}<span id="uid">{{ uid }}</span></p>
                            <p><a href="{% url 'polls:index' %}">Go Home</a></p>
                            <p><a a data-toggle="modal" data-target="#confirmIDModal">Get a new ID</a></p>
                            <p><a href="#nickform" data-toggle="collapse" aria-expanded="false" aria-controls="collapseExample">Set a Nickname</a></p>
                            <div class="collapse" id="nickform">
                                <form action="{%url 'polls:nick' %}?next={{ request.path|urlencode }}" method="post">
                                    {% csrf_token %}
                                    <div class="input-group">
                                        <input name="nick" type="text" class="form-control">
                                        <span class="input-group-btn">
                                            <button class="btn btn-default" type="submit">Submit</button>
                                        </span>
                                    </div>
                                </form>
                            </div>
                            <p><a href="{% url 'polls:post' %}">Create a new poll</a></p>
                            {%block sidebar%}{%endblock%}
                        </div>
                    </div>
                {%block sidecolumn%}{%endblock%}
                {% else %}
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <div>You need to <a href="{% url 'polls:login' %}?next={{ request.path|urlencode }}">login</a></div>
                        </div>
                    </div>
                {% endif %}
            </div>
            <div class="col-sm-9 col-lg-10">
                {% block content %} {% endblock %}
            </div>
        </div>
    </div>
    <footer class="footer">
        <div class="text-center container">
            <p class="text-muted">Created by Isaac Avram. <a href="https://bitbucket.org/avrisaac555/pollboard/issues?status=new&status=open">Report issues and request new features here</a></p>
        </div>
    </footer>
</body>
</html>

polls/templates/polls/detail.html
{% extends "polls/base.html" %}
{% load staticfiles %}

{%block head %}
<script src="{% static 'polls/script.js' %}"></script>
<script src="{% static 'polls/markdown.js' %}"></script>
<script src="{% static 'polls/to-markdown.js' %}"></script>
<script src="{% static 'polls/bootstrap-markdown.js' %}"></script>
{%endblock%}

{%block sidecolumn %}
{%if author%}
<div class="panel panel-info panel-sidebar">
    <div class="panel-heading"><h4>Author Panel</h4></div>
    <div class="panel-body">
        <p><a data-toggle="modal" data-target="#confirmDeleteModal">Delete this poll</a></p>
    </div>
</div>
{%endif%}
{%if nick.name in admin_nicks%}
<div class="panel panel-info panel-sidebar">
    <div class="panel-heading"><h4>Admin Panel</h4></div>
    <div class="panel-body">
        <p><a data-toggle="modal" data-target="#confirmDeleteModal">Delete this poll</a></p>
        {%if question.sticky %}
        <p><a href="{% url 'polls:question_sticky' question.id %}?next={{ request.path|urlencode }}">Unsticky this poll</a></p>
        {%else%}
        <p><a href="{% url 'polls:question_sticky' question.id %}?next={{ request.path|urlencode }}">Sticky this poll</a></p>
        {%endif%}
    </div>
</div>
{%endif%}
{%endblock%}

{%block modal%}
<div class="modal fade" id="confirmDeleteModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4>Confirm Delete</h4>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete this poll?</p>
                <p><b>This action cannot be undone!</b></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Never Mind</button>
                <a href="{% url 'polls:question_delete' question.id %}" type="button" class="btn btn-danger">Yes, delete it</a>
            </div>
        </div>
    </div>
</div>
{%endblock%}

{% block content %}
<div class="row">
    <div class="col-md-12 content-wrap">
        <h2 class="question-title">{{ question.question_text }}</h2>
        <p class="question-desc">{{ question.description|safe }}</p>
        {%if question.choice_set.all %}
        <form action="{% url 'polls:vote' question.id %}" method="post">
            {% csrf_token %}
            {% for choice in question.choice_set.all %}
            <div class='radio'>
                <label>
                    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
                    {{ choice.choice_text }}
                </label>
            </div>
            {% endfor %}
            <input type="submit" value="Vote" />
        </form>
        {%endif%}
    </div>
</div>
<div class="row">
    <div class="col-md-7 content-wrap">
        <h3>Comments</h3>
        {% if question.comments.all %}
        {% for comment in question.comments.all %}
            <div class="comment" id="{{comment.id_txt}}">
                <div class="comment-submitter" style="color: #{{comment.id_txt|slice:'6'}}"> <b>{{comment.id_txt}}</b> -
                    <span class="nick{%if comment.submitter_nick in admin_nicks %} admin{%endif%}">{%if comment.submitter_nick %}[{{ comment.submitter_nick }}]</span>{%endif%}
                    <span class="uid" style="color: #{{comment.submitter|slice:'6'}}">{{comment.submitter|slice:'20'}}</span>
                    <span class="actions">{%if nick.name in admin_nicks%}<a href="{% url 'polls:comment_delete' comment.id_txt %}?next={{ request.path|urlencode }}" class="delete-btn">Delete</a>{%endif%} <a class="reply-btn" id="{{comment.id_txt}}">Reply</a></span>
                </div>
                <div>{{comment.text|safe}}</div>
            </div>
        {%endfor%}
        {% else %}
            <p> There are no comments</p>
        {%endif%}
    </div>
</div>
<div class="row">
    <div class="col-md-7 comment-form">
        <form action="{% url 'polls:comment' question.id %}" method="post">
            <div class="form-group">
                <h3 id="comment-box">Post a new comment</h3>
                {% csrf_token %}
                <textarea class="form-control" type="textarea" name="comment_text" rows="10" data-provide="markdown" data-resize="vertical" placeholder="Comment, basic HTML supported"></textarea>
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
        </form>
    </div>
</div>
{%endblock%}

polls/templates/polls/index.html
{% extends "polls/base.html" %}

{% block content %}

{% if sticky_question_list %}
{% for question in sticky_question_list %}
    <div class="question sticky {% cycle '' 'highlighted' %}">
        <div class="question-id hidden-xs">[ {{question.id }} ]</div> 
        <div class="question-title" >
            <a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
            <span style="color: #{{question.submitter|slice:'6'}}"> {%if question.submitter_nick %}<b>[{{ question.submitter_nick }}]: </b>{%endif%}{{question.submitter|slice:"6"}}</span>
            <div>{{question.tagline}}</div>
        </div>
    </div>
{%endfor%}
<br />
{%endif%}
{% if latest_question_list %}
{% for question in latest_question_list %}
    <div class="question {% cycle '' 'highlighted' %}">
        <div class="question-id hidden-xs">[ {{question.id }} ]</div> 
        <div class="question-title" >
            <a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
            <span style="color: #{{question.submitter|slice:'6'}}"> {%if question.submitter_nick %}<b>[{{ question.submitter_nick }}]: </b>{%endif%}{{question.submitter|slice:"6"}}</span>
            <div>{{question.tagline}}</div>
        </div>
    </div>
{% endfor %}
{% else %}

<p> No questions available </p>

{% endif %}

{% endblock %}

polls/templates/polls/post.html
{% extends "polls/base.html" %}
{% load staticfiles %}

{%block head%}
<script src="{% static 'polls/post.js' %}"></script>
{%endblock%}

{% block content %}
<div class="row">
    <div class="col-md-5">
        <form action="{% url 'polls:post' %}" method="post">
            <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}" />
                <div class="form-group">
                    <h3>Question</h3>
                    <p><input name="title" type="text" class="form-control" placeholder="Title (max: 200)" /></p>
                    <p><input name="tagline" type="text" class="form-control" placeholder="Tagline (max: 140)" /></p>
                    <p><textarea type="textarea" class="form-control" name="description" rows="6" placeholder="Description, basic HTML supported"></textarea></p>
                </div>
                <div id="choice-list" class="form-group">
                    <h3>Choices</h3>
                    <div class="input-group p-space">
                        <input name="choice" type="text" class="form-control" placeholder="Choice" />
                        <span class="input-group-btn">
                            <button id="add-btn" class="btn btn-success" type="button"><span class="glyphicon glyphicon-plus"></span></button>
                        </span>
                    </div><!--/input-group -->
                </div><!--/form-group -->
            <button type="submit" class="btn btn-default">Submit</button>
        </form>
    </div>
</div>
{%endblock%}

polls/templates/polls/results.html
{% extends "polls/base.html" %}

{% block content %}

<h2>{{ question.question_text }}</h2>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

{% endblock %}